# Get The Data

In [94]:
with open(file='AOC_5_input.txt') as f:
    _data = f.read().split('\n')

data = []
for el in _data:
    data.append(el.split(' -> '))


In [95]:
import numpy as np
grid = np.zeros(shape=(10,10))
print(grid)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [96]:
for positions in data:
    x1 = eval(positions[0].split(',')[0])
    y1 = eval(positions[0].split(',')[1])
    x2 = eval(positions[1].split(',')[0])
    y2 = eval(positions[1].split(',')[1])
    
    if x1 == x2:
        for i in range(min(y1, y2), max(y1, y2) + 1):
            grid[i][x1] += 1
    elif y1 == y2:
        for i in range(min(x1, x2), max(x1, x2) + 1):
            grid[y1][i] += 1
    else:
        


In [97]:
print(np.count_nonzero(grid>1))

5
